version: "3.7"
services:
  client:
    build:
      context: ./client
    ports:
      - 8080:8080
    environment:
      - API_URL=http://api:3000
  api:
    build:
      context: ./api
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=your_database_username
      - DB_PASSWORD=your_database_password
      - DB_DATABASE=jira_development
      - JWT_SECRET=development12345

  db:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_USER=your_database_username
      - POSTGRES_PASSWORD=your_database_password
      - POSTGRES_DB=jira_development
    volumes:
      - "db-data:/var/lib/postgresql/data"

volumes:
  db-data:
